sudo: false

language: c

addons:
    apt:
        packages:
        - libgmp-dev

cache:
    directories:
    - $HOME/.stack/

env:
- ARGS="--resolver lts-4"
- ARGS="--resolver lts-5"
- ARGS="--resolver lts-6"
- ARGS="--resolver lts-7"
- ARGS="--resolver lts-8"
- ARGS="--resolver lts"
- ARGS="--resolver nightly"

before_install:
- mkdir -p ~/.local/bin
- export PATH=~/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip=1 -C ~/.local/bin '*/stack'

install:
- travis_wait stack $ARGS --no-terminal --skip-ghc-check setup
- travis_wait stack $ARGS --no-terminal --skip-ghc-check test --only-snapshot

script:
- stack $ARGS --no-terminal --skip-ghc-check build
